timeout: 120
service:
  externalPort: 3000
  internalPort: 3000
image:
  secrets:
  - name: skdigital-bonet-registry
ingress:
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
hostAliases:
- ip: "37.9.170.240"
  hostnames:
  - "eschranka1.slovensko.sk"
  - "eschranka.upvsfixnew.gov.sk"
  - "iamwse.slovensko.sk"
  - "iamwse.upvsfix.gov.sk"
  - "uir.slovensko.sk"
  - "uir.upvsfixnew.gov.sk"
  - "usr.slovensko.sk"
  - "usr.upvsfixnew.gov.sk"
livenessProbe:
  initialDelaySeconds: 20
  probeType: "exec"
  command:
  - "true"
readinessProbe:
  initialDelaySeconds: 20 
  probeType: "exec"
  command:
  - "true"
resources:
  requests:
    cpu: 5m
    memory: 380Mi
  limits:
    cpu: 2
    memory: 1024Mi
application:
  migrateCommand: ["bundle", "exec", "rails", "db:migrate"]
persistence:
  enabled: true
  volumes:
  - name: security-volume
    mount:
      path: /app/security
    claim:
      accessMode: ReadWriteMany
      size: 16M
      storageClass: manual
workers:
  clock:
    hostAliases:
    - ip: "37.9.170.240"
      hostnames:
      - "eschranka1.slovensko.sk"
      - "eschranka.upvsfixnew.gov.sk"
      - "iamwse.slovensko.sk"
      - "iamwse.upvsfix.gov.sk"
      - "uir.slovensko.sk"
      - "uir.upvsfixnew.gov.sk"
      - "usr.slovensko.sk"
      - "usr.upvsfixnew.gov.sk"
    replicaCount: "1"
    command: ["bundle", "exec", "clockwork", "config/clock.rb"]
    terminationGracePeriodSeconds:  60
    livenessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 10
      probeType: "exec"
      command:
        - "true"
    readinessProbe:
      probeType: "exec"
      command:
        - "true"
  worker:
    hostAliases:
    - ip: "37.9.170.240"
      hostnames:
      - "eschranka1.slovensko.sk"
      - "eschranka.upvsfixnew.gov.sk"
      - "iamwse.slovensko.sk"
      - "iamwse.upvsfix.gov.sk"
      - "uir.slovensko.sk"
      - "uir.upvsfixnew.gov.sk"
      - "usr.slovensko.sk"
      - "usr.upvsfixnew.gov.sk"
    replicaCount: "1"
    command: ["bundle", "exec", "rake", "jobs:work"]
    terminationGracePeriodSeconds:  60
    livenessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 10
      probeType: "exec"
      command:
        - "true"
    readinessProbe:
      probeType: "exec"
      command:
        - "true"
