default: &default
  adapter: postgresql
  encoding: unicode
  pool: 50

development:
  <<: *default
  database: podaas_development
  username: postgres
  password: password

test:
  <<: *default
  database: podaas_test
  username: postgres
  password: password

staging:
  url: <%= ENV['DATABASE_URL'] %>
  pool: 30

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: 50
