---
- service: name=docker state=started

- name: Build slovensko-sk-api and push it to a private repo
  docker_image:
    build:
      path: ../
      dockerfile: Dockerfile
    name: 'gcr.io/{{ project_id }}/slovensko-sk-api'
    tag: latest
    push: yes
    force: yes
    source: build
    state: present

- name: Initialize db from cloud run
  command: >
    gcloud run deploy slovensko-sk-api-db
      --project '{{ project_id }}'
      --image gcr.io/{{ project_id }}/slovensko-sk-api:latest
      --memory 512Mi
      --platform managed
      --region '{{ location }}'
      --allow-unauthenticated
      --add-cloudsql-instances '{{ sql_instance_res.connectionName }}'
      --set-env-vars DATABASE_URL='postgres://{{sql_instance.db_user}}:{{sql_instance.db_password}}@{{sql_instance_res.ipAddresses[0].ipAddress}}:5432/{{sql_instance.db_name}}'
      --set-env-vars REDIS_URL='redis://{{redis.host}}:{{redis.port}}'
      --vpc-connector sk-api-sql-connector
      --set-env-vars RAILS_ENV=production
      --set-env-vars SECRET_KEY_BASE=d7af1c4be8e977a23f0e0549c04bcd4b4289c8767d22a3af2531e86e7e7936fdc0d48ea719ab94013405e2c28d9763610eae23dab384599be8210864419c9bfc
      --set-env-vars API_TOKEN_PUBLIC_KEY_FILE=security/api-token.public.pem
      --set-env-vars EFORM_SYNC=false
      --set-env-vars UPVS_ENV=dev
      --set-env-vars UPVS_SSO_SUPPORT=true
      --set-env-vars UPVS_STS_KS_FILE=security/einvoice-dev.keystore
      --set-env-vars UPVS_STS_KS_ALIAS=einvoice
      --set-env-vars UPVS_STS_KS_PASSWORD=password
      --set-env-vars UPVS_STS_KS_PRIVATE_PASSWORD=password
      --set-env-vars UPVS_TLS_TS_FILE=security/upvs-dev.truststore
      --set-env-vars UPVS_TLS_TS_PASSWORD=password
      --set-env-vars ^;^LOGIN_CALLBACK_URLS=http://localhost:3000,https://web-app.dev.filipsladek.com
      --set-env-vars ^;^LOGOUT_CALLBACK_URLS=http://localhost:3000,https://web-app.dev.filipsladek.com
      --set-env-vars OBO_TOKEN_PRIVATE_KEY_FILE=security/obo-token.private.pem
      --set-env-vars UPVS_IDP_METADATA_FILE=security/upvs-dev-idp.metadata.xml
      --set-env-vars UPVS_SP_METADATA_FILE=security/einvoice-dev.signed.metadata.xml
      --set-env-vars UPVS_SP_KS_FILE=security/einvoice-dev.keystore
      --set-env-vars UPVS_SP_KS_ALIAS=einvoice
      --set-env-vars UPVS_SP_KS_PASSWORD=password
      --set-env-vars UPVS_SP_KS_PRIVATE_PASSWORD=password
      --command rails
      --args db:create
      --args db:migrate
  ignore_errors: yes

- name: Deploy cloud run slovensko-sk-api
  command: >
    gcloud run deploy slovensko-sk-api
      --project '{{ project_id }}'
      --image gcr.io/{{ project_id }}/slovensko-sk-api:latest
      --memory 2048Mi
      --platform managed
      --region '{{ location }}'
      --allow-unauthenticated
      --add-cloudsql-instances '{{ sql_instance_res.connectionName }}'
      --set-env-vars DATABASE_URL='postgres://{{sql_instance.db_user}}:{{sql_instance.db_password}}@{{sql_instance_res.ipAddresses[0].ipAddress}}:5432/{{sql_instance.db_name}}'
      --set-env-vars REDIS_URL='redis://{{redis.host}}:{{redis.port}}'
      --vpc-connector sk-api-sql-connector
      --set-env-vars RAILS_ENV=production
      --set-env-vars SECRET_KEY_BASE=d7af1c4be8e977a23f0e0549c04bcd4b4289c8767d22a3af2531e86e7e7936fdc0d48ea719ab94013405e2c28d9763610eae23dab384599be8210864419c9bfc
      --set-env-vars API_TOKEN_PUBLIC_KEY_FILE=security/api-token.public.pem
      --set-env-vars EFORM_SYNC=false
      --set-env-vars UPVS_ENV=dev
      --set-env-vars UPVS_SSO_SUPPORT=true
      --set-env-vars UPVS_STS_KS_FILE=security/einvoice-dev.keystore
      --set-env-vars UPVS_STS_KS_ALIAS=einvoice
      --set-env-vars UPVS_STS_KS_PASSWORD=password
      --set-env-vars UPVS_STS_KS_PRIVATE_PASSWORD=password
      --set-env-vars UPVS_TLS_TS_FILE=security/upvs-dev.truststore
      --set-env-vars UPVS_TLS_TS_PASSWORD=password
      --set-env-vars ^;^LOGIN_CALLBACK_URLS=http://localhost:3000,https://web-app.dev.filipsladek.com
      --set-env-vars ^;^LOGOUT_CALLBACK_URLS=http://localhost:3000,https://web-app.dev.filipsladek.com
      --set-env-vars OBO_TOKEN_PRIVATE_KEY_FILE=security/obo-token.private.pem
      --set-env-vars UPVS_IDP_METADATA_FILE=security/upvs-dev-idp.metadata.xml
      --set-env-vars UPVS_SP_METADATA_FILE=security/einvoice-dev.signed.metadata.xml
      --set-env-vars UPVS_SP_KS_FILE=security/einvoice-dev.keystore
      --set-env-vars UPVS_SP_KS_ALIAS=einvoice
      --set-env-vars UPVS_SP_KS_PASSWORD=password
      --set-env-vars UPVS_SP_KS_PRIVATE_PASSWORD=password

- name: Domain mapping upvs
  command: >
    gcloud beta run domain-mappings create
      --project '{{ project_id }}'
      --service slovensko-sk-api
      --domain upvs.dev.filipsladek.com
      --platform managed
      --region '{{ location }}'
  ignore_errors: yes

- name: Domain mapping upvs
  command: >
    gcloud beta run domain-mappings describe
      --project '{{ project_id }}'
      --domain upvs.dev.filipsladek.com
      --platform managed
      --region '{{ location }}'
  register: upvs_domain_mapping_output

- debug:
    msg: upvs_domain_mapping_output={{ upvs_domain_mapping_output }}
