---
- name: Delete redis instance
  gcp_redis_instance:
    name: '{{ redis_instance_name }}'
    tier: STANDARD_HA
    memory_size_gb: 1
    region: '{{ location }}'
    redis_version: REDIS_3_2
    display_name: Auth db
    reserved_ip_range: 192.168.0.0/29
    project: '{{ project_id }}'
    state: absent
